[package]
name = "irys-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
reth-cli-util.workspace = true
reth-irys-cli.workspace = true
reth-irys-rpc.workspace = true
reth-irys-node = { workspace = true, features = ["js-tracer"] }
reth-irys-chainspec.workspace = true
reth-irys-consensus.workspace = true
reth-irys-evm.workspace = true
reth-irys-payload-builder.workspace = true
reth-irys-primitives.workspace = true
reth-irys-forks.workspace = true

clap = { workspace = true, features = ["derive", "env"] }
tracing.workspace = true

[lints]
workspace = true

[features]
default = ["jemalloc", "reth-irys-evm/portable"]

jemalloc = ["reth-cli-util/jemalloc", "reth-irys-cli/jemalloc"]
jemalloc-prof = ["reth-cli-util/jemalloc-prof"]
tracy-allocator = ["reth-cli-util/tracy-allocator"]

asm-keccak = ["reth-irys-cli/asm-keccak", "reth-irys-node/asm-keccak"]

dev = [
    "reth-irys-cli/dev",
    "reth-irys-primitives/arbitrary",
]

min-error-logs = ["tracing/release_max_level_error"]
min-warn-logs = ["tracing/release_max_level_warn"]
min-info-logs = ["tracing/release_max_level_info"]
min-debug-logs = ["tracing/release_max_level_debug"]
min-trace-logs = ["tracing/release_max_level_trace"]

[[bin]]
name = "op-reth"
path = "src/main.rs"
